### ISSUE TITLE
Version for Orange Pi PC please?

### ISSUE THREAD

**Issue by marksev1** [steelsquid/steelsquid-kiss-os#1]
Could you maybe make a version for Orange Pi PC, since it is very cheap and powerful board. And it has GPIO functionality via WiringOPI fork.

**Comment by steelsquid** [comment]
Thanks for the du suggestion :-)
But sorry, do not think I will have time for it :-(

**Comment by marksev1** [comment]
Is this steelsquid-kiss-os just a big python program on top of Raspbian? Do you maybe know which parts of the python scripts are specific to Raspberry pi, since because probably I could use a lot of things already on the Orange pi.
